/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javaapplication71;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author LAB PROGRAMMING 1
 */
public class coba extends javax.swing.JFrame {

    /**
     * Creates new form coba
     */
    model_mahasiswa model;

    public coba() {
        initComponents();
        model = new model_mahasiswa();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rb_group = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        bt_Edit = new javax.swing.JButton();
        bt_simpan = new javax.swing.JButton();
        bt_hapus = new javax.swing.JButton();
        bt_keluar = new javax.swing.JButton();
        lbNim = new javax.swing.JLabel();
        tf_Nim = new javax.swing.JTextField();
        bt_Cari = new javax.swing.JButton();
        lbNama = new javax.swing.JLabel();
        tf_Nama = new javax.swing.JTextField();
        lbKelas = new javax.swing.JLabel();
        rb_a = new javax.swing.JRadioButton();
        rb_b = new javax.swing.JRadioButton();
        rb_c = new javax.swing.JRadioButton();
        lbMatkul = new javax.swing.JLabel();
        cb_Matkul = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 51, 51));

        jPanel1.setBackground(new java.awt.Color(51, 255, 51));

        bt_Edit.setText("Edit");
        bt_Edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_EditActionPerformed(evt);
            }
        });

        bt_simpan.setText("Simpan");
        bt_simpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_simpanActionPerformed(evt);
            }
        });

        bt_hapus.setText("Hapus");
        bt_hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_hapusActionPerformed(evt);
            }
        });

        bt_keluar.setBackground(new java.awt.Color(204, 0, 51));
        bt_keluar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        bt_keluar.setForeground(new java.awt.Color(255, 255, 255));
        bt_keluar.setText("Keluar");
        bt_keluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_keluarActionPerformed(evt);
            }
        });

        lbNim.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lbNim.setText("NIM");
        lbNim.setAlignmentX(0.5F);

        bt_Cari.setText("CARI");
        bt_Cari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_CariActionPerformed(evt);
            }
        });

        lbNama.setText("Nama");

        lbKelas.setText("Kelas");

        rb_a.setBackground(new java.awt.Color(51, 255, 51));
        rb_group.add(rb_a);
        rb_a.setText("A");
        rb_a.setActionCommand("a");

        rb_b.setBackground(new java.awt.Color(51, 255, 51));
        rb_group.add(rb_b);
        rb_b.setText("B");
        rb_b.setActionCommand("b");

        rb_c.setBackground(new java.awt.Color(51, 255, 51));
        rb_group.add(rb_c);
        rb_c.setText("C");
        rb_c.setActionCommand("c");

        lbMatkul.setText("Mata Kuliah");

        cb_Matkul.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih Matkul", "kalkulus", "alpro", "matdis", "bindo" }));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(bt_Edit)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bt_simpan, javax.swing.GroupLayout.DEFAULT_SIZE, 79, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bt_hapus, javax.swing.GroupLayout.DEFAULT_SIZE, 76, Short.MAX_VALUE)
                        .addGap(44, 44, 44)
                        .addComponent(bt_keluar, javax.swing.GroupLayout.DEFAULT_SIZE, 76, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbNim, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbKelas))
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(tf_Nim, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(bt_Cari, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbNama)
                            .addComponent(lbMatkul))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(rb_a)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(rb_b)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(rb_c))
                                    .addComponent(cb_Matkul, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(148, 148, 148))
                            .addComponent(tf_Nama))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(bt_Cari)
                    .addComponent(tf_Nim, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbNim, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbNama)
                    .addComponent(tf_Nama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbKelas)
                    .addComponent(rb_a)
                    .addComponent(rb_b)
                    .addComponent(rb_c))
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbMatkul)
                    .addComponent(cb_Matkul, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bt_Edit)
                    .addComponent(bt_simpan)
                    .addComponent(bt_hapus)
                    .addComponent(bt_keluar))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bt_CariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_CariActionPerformed
        // TODO add your handling code here:
        ResultSet data = model.cariData(tf_Nim.getText());
        try {
            if (data.next()) {
                tf_Nim.setText(data.getString("nim"));
                tf_Nama.setText(data.getString("nama"));
                switch (data.getString("kelas")) {
                    case "a":
                        rb_group.setSelected(rb_a.getModel(), true);
                        break;
                    case "b":
                        rb_group.setSelected(rb_b.getModel(), true);
                        break;
                    case "c":
                        rb_group.setSelected(rb_c.getModel(), true);
                        break;
                }
                switch (data.getString("matkul")) {
                    case "kalkulus":
                        cb_Matkul.setSelectedIndex(0);
                        break;
                    case "alpro":
                        cb_Matkul.setSelectedIndex(1);
                        break;
                    case "matdis":
                        cb_Matkul.setSelectedIndex(2);
                        break;
                    case "bindo":
                        cb_Matkul.setSelectedIndex(3);
                        break;
                }
            }
        } catch (SQLException ex) {
            Logger.getLogger(coba.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_bt_CariActionPerformed

    private void bt_keluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_keluarActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_bt_keluarActionPerformed

    private void bt_EditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_EditActionPerformed
        // TODO add your handling code here:
        boolean edit = model.editData(tf_Nim.getText(), tf_Nama.getText(), rb_group.getSelection().getActionCommand(), cb_Matkul.getSelectedItem().toString());
        if (edit == true)
            JOptionPane.showMessageDialog(null, "Data berhasi diedit");
        else
            JOptionPane.showMessageDialog(null, "Data gagal diedit");
    }//GEN-LAST:event_bt_EditActionPerformed

    private void bt_simpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_simpanActionPerformed
        // TODO add your handling code here:
        boolean simpan = model.simpanData(tf_Nim.getText(), tf_Nama.getText(), rb_group.getSelection().getActionCommand(), cb_Matkul.getSelectedItem().toString());
        if (simpan == true)
            JOptionPane.showMessageDialog(null, "Data berhasi disimpan");
        else
            JOptionPane.showMessageDialog(null, "Data gagal disimpan");
    }//GEN-LAST:event_bt_simpanActionPerformed

    private void bt_hapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_hapusActionPerformed
        // TODO add your handling code here:
       int option = JOptionPane.showConfirmDialog(null, "Data akan dihapus ???","Penghapusan data",JOptionPane.YES_NO_OPTION,JOptionPane.WARNING_MESSAGE);
       if(option == JOptionPane.YES_OPTION){
            model.hapusData(tf_Nim.getText());
               JOptionPane.showMessageDialog(null,"Data berhasil dihapus");
       }
    }//GEN-LAST:event_bt_hapusActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(coba.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(coba.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(coba.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(coba.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new coba().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_Cari;
    private javax.swing.JButton bt_Edit;
    private javax.swing.JButton bt_hapus;
    private javax.swing.JButton bt_keluar;
    private javax.swing.JButton bt_simpan;
    private javax.swing.JComboBox<String> cb_Matkul;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbKelas;
    private javax.swing.JLabel lbMatkul;
    private javax.swing.JLabel lbNama;
    private javax.swing.JLabel lbNim;
    private javax.swing.JRadioButton rb_a;
    private javax.swing.JRadioButton rb_b;
    private javax.swing.JRadioButton rb_c;
    private javax.swing.ButtonGroup rb_group;
    private javax.swing.JTextField tf_Nama;
    private javax.swing.JTextField tf_Nim;
    // End of variables declaration//GEN-END:variables
}
